title: Justin Anthony Kapelke Jørgensen
description: Datamatikerstuderende 
site_title: '@JustinAnthonyKapelke - Justin Anthony Kapelke Jørgensen'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: JustinAnthonyKapelke
blog_url: https://justinanthonykapelke.github.io/Portfolio2/
email: abhishek@nagekar.com
keybase_username: JustinAnthonyKapelke

# absolute or relative
profile_picture: assets/images/Justin.png

# Google Analytics ID
google_analytics: 
